// <auto-generated />
namespace Smart_Scale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ósma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ósma));
        
        string IMigrationMetadata.Id
        {
            get { return "202004171800061_ósma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
